# fly.toml file generated for obsidian-clipper-extension on 2023-03-18T12:35:08-05:00

app = "obsidian-clipper-extension"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "dfw"
processes = []

[env]
  PHX_HOST = "obsidian-clipper-extension.fly.dev"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
